sudo: false

addons:
  apt:
    packages:
      - libexpat1-dev
      - gettext
      - liblcms2-dev
      - libmagickwand-dev
      - libopenexr-dev
      - libcfitsio3-dev
      - libgif-dev
      - libgs-dev
      - libgsf-1-dev
      - libmatio-dev
      - libopenslide-dev
      - liborc-0.4-dev
      - libpango1.0-dev
      - libpoppler-glib-dev
      - librsvg2-dev
      - libwebp-dev
        # missing on trusty, unfortunately
        # - libwebpmux2
      - libfftw3-dev
      - libglib2.0-dev

cache:
  - bundler

language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

before_script:
  - bundle exec rake build

script: 
  - bundle exec rake

gemfile:
  - Gemfile
